defaultFont = 14
Component.arc = 10
Button.arc = 10
TextComponent.arc = 10
Component.focusWidth = 1
Component.innerFocusWidth = 0
Button.margin = 9,16,9,16
ComboBox.padding = 8,10,8,10
Spinner.padding = 8,10,8,10
TextField.margin = 9,12,9,12
Table.rowHeight = 38
TableHeader.height = 40
Table.showHorizontalLines = false
Table.showVerticalLines = false
ScrollBar.width = 10
ScrollPane.arc = 10
TitlePane.unifiedBackground = true
